<<<<<<< HEAD
# Generated by Django 3.2.6 on 2022-11-17 04:40
=======
# Generated by Django 3.2.6 on 2022-11-17 06:29
>>>>>>> 42c6a8dfde977d4de88839f64c9d032fa133716f

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genreid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Top_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=200)),
                ('backdrop_path', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('genres', models.ManyToManyField(blank=True, related_name='top_movies', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Now_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=200)),
                ('backdrop_path', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('genres', models.ManyToManyField(blank=True, related_name='now_movies', to='movies.Genre')),
            ],
        ),
    ]
